### ISSUE TITLE
Metric distance calculation

### ISSUE THREAD

**Issue by tonyp** [ljmerza/waze-card#1]
It seems like the card converts the metric units wrong.

It shoes:
> Distance: 61.97km
> While the real distance is 38.508km

So the addon is converting the distance to kilometers while it already is using kilometers.
"unit_system" is set to "metric". I'm using a sensor within the EU region.

I have fixed it locally by removing this line in the code:
`if(this._hass.config.unit_system.length !== 'mi') distance = distance * 1.60934;`

**Comment by ljmerza** [comment]
I've had a few issues with the wrong conversion. Looks like the waze api isn't consistent when giving back the units.

**Comment by ljmerza** [comment]
I've updated some code let me know if it worked. Thanks

**Comment by mikeage** [comment]
I'm having the same problem:
```
Feb 17 10:33:05 raspberrypi hass[5808]: From: XXXX,YYYY - to: AAAA,BBBB
Feb 17 10:33:05 raspberrypi hass[5808]: 2019-02-17 10:33:05 INFO (Thread-9) [WazeRouteCalculator.WazeRouteCalculator] From: XXXX,YYYY - to: AAAA,BBBB
Feb 17 10:33:08 raspberrypi hass[5808]: Time 29.45 - 41.93 minutes, distance 35.17 - 36.06 km.
Feb 17 10:33:08 raspberrypi hass[5808]: 2019-02-17 10:33:08 INFO (Thread-9) [WazeRouteCalculator.WazeRouteCalculator] Time 29.45 - 41.93 minutes, distance 35.17 - 36.06 km.
```
But in the card, I see 58.03km. 
Card config:
```yaml
entities:
  - entity: sensor.time_to_work
    name: Work
    zone: zone.work
type: 'custom:waze-card'
```
Card version 1.2.0

**Comment by ljmerza** [comment]
Ok I ended up just removing any distance calculations from this card and solely relying on the distance calculation of the waze component. Hopefully, this can finally resolve this issue and if not then at this point it's the waze component that's giving me the wrong data.

**Comment by mikeage** [comment]
Thanks, I’ll check tonight. It’s weird because the code looked totally fine...no idea what was going on.

**Comment by ljmerza** [comment]
Yeah the waze dev got back to me and said in the version home assistant
uses 0.6 the waze server to get the distance is randomly selected but in
the 0.8 version that was hopefully fixed. Looks like there's a pr on home
assistant to upgrade to 0.8 but it wouldn't be included until 0.89 release.
I did initially have the conversion code in my card because my waze
component show distance in kilometers even though i have imperial set for
my home assistant config.

**Comment by mikeage** [comment]
looking better for me (I have metric set, region of IL). Hopefully the waze package will make it; it looks non trivial, but it has someone assigned at least.

**Comment by ljmerza** [comment]
doesn't look like the new version of waze fixes the distance issue. I added options to force conversions as a last resort in v1.3.0
