### ISSUE TITLE
iOS 10 issue

### ISSUE THREAD

**Issue by nesty156** [ljmerza/waze-card#2]
Hi your card works fine on desktop Or my iOS 12 device but on my iOS 10 device it says: Custom element doesn't exist: waze-card. Any idea why its happening? Thank you.

**Comment by ljmerza** [comment]
Make sure your browser version supports web components. Do all other cards work just not this one?

**Comment by it1515** [comment]
yeah some works and some not :D

**Comment by ljmerza** [comment]
It sounds like maybe that safari version doesn't support certain features some cards are using. I don't own an apple phone so you'd have to somehow get the error message safari is displaying in the console.

**Comment by ljmerza** [comment]
DEPRECATED use https://github.com/ljmerza/travel-time-card
