### ISSUE TITLE
Make entity name dynamic

### ISSUE THREAD

**Issue by danlakey** [ljmerza/waze-card#3]
Hello and that you so much for this great custom card! I've implemented your card in the following way:

- I have a template sensor that is getting updated via an automation with address location pulled from a Google calendar attribute.

- My waze sensor is set for the origin to be my phone's location and my destination to be this template sensor's location.

So based off of my next calendar entry, my destination location is being set dynamically throughout the day. Does your card have a way that the entity name can be set dynamically as well? 

Thank you

**Comment by ljmerza** [comment]
DEPRECATED use https://github.com/ljmerza/travel-time-card
